### PR TITLE
Save tooltipArgs before checking for tooltip (except arg1).

### PR DESCRIPTION
**Pull request by WFrancois**
Hey ! Here's a fix for #49

The issue was that if a player doesn't have a profile, then the tooltipArgs wasn't saved so when displaying the player's tooltip, it didn't know what to show.

FYI, there's still an issue when creating a group, but I don't really know how you would want to handle it.
The issue is that when forming a group, you technically can't see your profile (we discussed about that when setting that up). So if an applicant doesn't have a profile and your config is set to not position automatically, then it show the profile by default (yours), but doesn't highlight the dungeon.

So, I don't know how you want to handle that !

A possible solution would be that if the position is manual, then instead of displaying the "default profile", it display yours, but not a fan of this solution , as it adds complexity to the code.

### CODE REVIEW

**Comment by jahraphael** [comment]
So it seemed a lot more reliable now, but I was still seeing some problems:

image

Will have to think on the issue about creating a group.

For now, I think what you have is an improvement over what's there, so I think let's go ahead and merge it, then we can follow up with another PR to further improve this or make the other change you mentioned.

**Comment by WFrancois** [comment]
Hm, wondering what is the issue with your image ?

**Comment by jahraphael** [comment]
I was expecting LOWR to be highlighted.

Maybe what's screwing it up is because this person has the run marked as Normal rather than M+?

**Comment by WFrancois** [comment]
It's Lower **Blackrock** Spire :p 

But yeah, it doesn't mark it if it's not Mythic Keystone anyway :) (so eg The Arcway (Mythic) won't highlight)

**Comment by jahraphael** [comment]
😭 

Haha. Indeed it is, okay.

**Pull request merged**
