### PR TITLE
Feature/my profile

### PR DESCRIPTION
**Pull request by WFrancois**
Hey !

Here's the PR for the new feature, Raider.IO Profile.

# Feature
- When opening `Group Finder` frame, display my Raider.IO Profile ([example](https://file.wisak.me/f/VbHEQYRKHn.png))
- Display this frame next to the tooltip of the group / player when looking for a group/member
- Using a modifier will switch to display the tooltip of this leader/player ([example](https://file.wisak.me/f/sE6uzIlnhJ.png))

# Profile
A Raider.IO Profile displays : 
- Player Score
- Main Score
- Best run for each dungeon

# Options
[In game](https://file.wisak.me/f/VETQrfRr4X.png)
- Enabling / Disabling this feature (default: enable)
- Enabling / Disabling the use of the modifier (default: enable)
- Allowing the possibility to reverse the use of the modifier (with this enable, the default will be the leader/player tooltip, and using a modifier will show your own profile) (default: disable)

### CODE REVIEW

**Comment by jahraphael** [comment]
This is looking great! Only problem I see right now is the tooltip still shows "My Profile" when I am hovering over people who are queued up for a group I've formed. Modifier didn't seem to do anything there either.

We just need to make sure that the tooltip there defaults to showing the applicant's info. Modifier isn't 100% necessary there.

**Comment by jahraphael** [comment]
I tried to reproduce the problem I ran into last night, but was unable to. Did you find something that made you think it should be fixed now?

Here are a few things I think we should address:

**1/4)** I think we should tweak the text for the options in the RaiderIO config. Here's my suggestions:

```
L.TOOLTIP_PROFILE = "Profile Tooltip Customization"
L.SHOW_RAIDERIO_PROFILE = "Show Profile Tooltip in Dungeon Finder"
L.SHOW_RAIDERIO_PROFILE_DESC = "Show the Raider.IO Profile Tooltip in the Dungeon Finder"
L.SHOW_LEADER_PROFILE = "Allow Profile Tooltip Modifier"
L.SHOW_LEADER_PROFILE_DESC = "Hold down a modifier (shift/ctrl/alt) to toggle Profile Tooltip between Personal/Leader Profile."
L.INVERSE_PROFILE_MODIFIER = "Invert the Profile Tooltip Toggle"
L.INVERSE_PROFILE_MODIFIER_DESC = "Enabling this will invert the behavior of the Profile Tooltip modifier (shift/ctrl/alt): hold to toggle the view between Personal/Leader profile or Leader/Personal profile."
```

I also relabeled the other tooltip section to be more clear that it refers to the Score tooltip: ```L.TOOLTIP_CUSTOMIZATION = "Score Tooltip Customization"```

**2/4)** Enlarge /raiderio pane so bottom isn't clipped so close to the button: image

**3/4)** Move the whole "Profile Tooltip Customization" section in config above the "Copy Raider.IO URL" block. This will put the two customization features near each other. Note: in spacing, aim to have as much vertical padding below the buttons as we have above the top of the text in the header: 
image

**4/4)** Can you make this PR to go to a new branch? I'd like to do the initial release of the feature on Alpha before we put it into master.

Thanks!

**Comment by WFrancois** [comment]
Hey !

> Did you find something that made you think it should be fixed now?

I really think you didn't have the latest when you tried, because I run into the same issue as you (profile tooltip being displayed on every tooltip. For that I did [this fix](https://github.com/jahraphael/raiderio-addon/pull/33/commits/1c261849dac2e7f3fcbabf93122d2326334a2cb2)
So really weird that you still had that bug :/

> I think we should tweak the text for the options in the RaiderIO config
No problem for that, I'm usually not the best when it comes to naming ^^'

> Enlarge /raiderio pane
> Move the whole "Profile Tooltip Customization" section in config above the "Copy Raider.IO URL" block.
Sure, will do that tonight !

> Can you make this PR to go to a new branch?
Done :heavy_check_mark:

**Comment by WFrancois** [comment]
Ok, all changes done, should be good 👍

**Pull request merged**
