### PR TITLE
Force player when sticked to PVEFrame

### PR DESCRIPTION
**Pull request by WFrancois**
Hey !

This PR fixes the bug where, if you opened the PVEFrame and you have someone in hover, then it will display this player's profile.

What I did in this PR is add a `force` argument when updating profile frame (replacing forcePlayer), that can take 2 values : 
- `target`: same behaviour as before when `forcePlayer` was set to true, so it only displays target's profile (used when forming group)
- `player`: force the frame to display your profile instead of what is saved in the `tooltipArgs`. This is used when setting the `profileTooltip` near the PVEFrame.

### CODE REVIEW

**Comment by jahraphael** [comment]
I think what's confusing me in this code is that the comments state that when force == "target" that it should force to target, but it never sets arg1 to "target" in that code.

Is the expectation that tooltipArgs[1] is "target" in these situations?

**Comment by WFrancois** [comment]
Yeah ,I get what you mean.
When I say ` target` , I don't say the "blizzard target" (so when you target someone), but more the "raiderio target", so wen you hover someone (which is what is stored in the `tooltipArgs[1]`).

So if this in force target, I only use the `tooltipArgs[1]` information and don't care about other option (like modifier, option and so on).

**Comment by jahraphael** [comment]
Okay - I would say the change we should make then is just to update the comment to more accurately state that:

- "force" is not a unit, so "target" doesn't mean the actual target. A better term than "target" here would be ideal, since I think it will be easy to think this means a unit. But I don't have a suggestion on term atm.

- The comment should probably state that there are 3 modes for "force": "player", "target", and then the behavior when "force" isn't supplied.

**Comment by WFrancois** [comment]
Ok, made the modification, what do you think ?

**Pull request merged**
